# Informed by https://keliris.dev/articles/setup-rust-github-actions.
# Special thanks to Alexander Keliris (@Rigellute)!
name: 'CI'

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: moonrepo/setup-rust@v1
        with:
          components: rustfmt
      - name: Check formatting
        run: cargo fmt --all --check

  lint:
    name: Lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # Not needed—for now.
          # - windows-latest
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: moonrepo/setup-rust@v1
        with:
          # bins: cargo-make
          components: clippy
      - name: Run linter
        # run: cargo make lint
        run: cargo clippy

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # Not needed—for now.
          # - macos-latest
          # - windows-latest
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: moonrepo/setup-rust@v1
        with:
          bins: cargo-make, cargo-nextest
      - name: Run tests
        run: cargo make test
